// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("API.Models.Coins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ask")
                        .HasColumnType("REAL");

                    b.Property<double>("bid")
                        .HasColumnType("REAL");

                    b.Property<string>("buy")
                        .HasColumnType("TEXT");

                    b.Property<string>("market")
                        .HasColumnType("TEXT");

                    b.Property<double>("rate")
                        .HasColumnType("REAL");

                    b.Property<string>("rateType")
                        .HasColumnType("TEXT");

                    b.Property<string>("sell")
                        .HasColumnType("TEXT");

                    b.Property<double>("spotRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
